"""GENERATED pairing/function/parameter/interface tables — do not hand-edit.

Regenerated by ``tools/gen_codes.py`` (docs/11 WP1) from the frozen vendor snapshots in
``tools/vendor/``; see ``NOTICE`` for licence attribution.
"""

from freeathome2mqtt.sysap.codes.functions import Function
from freeathome2mqtt.sysap.codes.interfaces import Interface
from freeathome2mqtt.sysap.codes.pairings import Pairing
from freeathome2mqtt.sysap.codes.parameters import Parameter

__all__ = ["Function", "Interface", "Pairing", "Parameter"]
