"""GENERATED pairing/function/parameter/interface tables — do not hand-edit.

Regenerated by ``tools/gen_codes.py`` (docs/11 WP1). Until WP1 lands this package is empty; the
licence terms for the vendored tables are resolved in ADR-002 (docs/00-overview-and-decisions.md).
"""
